version: 2.1
jobs:
  test:
    docker:
      - image: "circleci/node"
    steps:
      - checkout
      - run: cd src && npm test

workflows:
   version: 2
   test-and-deploy:
     jobs:
      - test
